### ISSUE TITLE
Confirmation required for fields for Project class

### ISSUE THREAD

**Issue by yulqen** [yulqen/dbasik#11]
@banillie 

It would be helpful to confirm the necessary fields for a Project object. We discussed this briefly yesterday. The project is fundamental to some of the work ahead on the Returns API, so it would be good to get this sorted.

Currently, the app is crashing when trying to view a project detail page because I have hard-coded some fields from the [old] test datamap to be used in the `context` for the view which shows a single `Project` (see [this function](https://github.com/yulqen/dbasik/blob/867429d452c02a0d4fdd499cd503896edae3f0dc/dbasik/register/views.py#L247)). That is completely the wrong approach - we should be using fields from the `Project` model only for this (i.e. we should expect the user to enter stuff like `SRO Name`, `Working Contact Name` as part of the register, not rely on it coming in from a return spreadsheet). 

The current Project model is [here](https://github.com/yulqen/dbasik/blob/867429d452c02a0d4fdd499cd503896edae3f0dc/dbasik/register/models.py#L226) and looks like:

```python
class Project(AppModel):
    name = models.CharField(max_length=255, blank=False)
    slug = AutoSlugField(populate_from=['name'])
    dependencies = models.ManyToManyField("Project", blank=True)
#   mandate = models.OneToOneField(Mandate, on_delete=models.CASCADE)
#   portfolio_initialisation = models.OneToOneField(
#       PortfolioInitialisation, on_delete=models.CASCADE, related_name="project_portfolio_initialisation"
#   )
#   mandate_active = models.BooleanField(default=False)
    tier = models.ForeignKey(Tier, on_delete=models.CASCADE)
    project_type = models.ForeignKey(ProjectType, on_delete=models.CASCADE, null=True)
    stage = models.ForeignKey(ProjectStage, on_delete=models.CASCADE, null=True)
#   dft_group = models.ForeignKey(DfTGroup, on_delete=models.CASCADE, null=True)
#   sro = models.ForeignKey(
#       Employee,
#       on_delete=models.CASCADE,
#       blank=True,
#       null=True,
#       related_name="project_sro",
#   )
#   director = models.ForeignKey(
#       Employee,
#       on_delete=models.CASCADE,
#       blank=True,
#       null=True,
#       related_name="project_director",
#   )
#   agency_delivery_partner = models.ForeignKey(
#       Organisation, on_delete=models.CASCADE, blank=True, null=True
#   )
    start_date = models.DateField(blank=True, null=True, )
    planned_end_date = models.DateField(blank=True, null=True)
    baseline_wlc = models.FloatField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('register:project_list')

    def __str__(self):
        return self.name
```
Some of the fields have been commented out for now - I was only experimenting with the minimal number of likely fields anyway to get things move (`Tier`, `ProjectStage`, etc).

Probably the best place to start is with the [models.py](https://github.com/yulqen/dbasik/blob/master/dbasik/register/models.py) - there are likely dependencies in here which will need fleshing out (or deleting) as appropriate, .e.g `Deliverable`, `Strategic Outcome`, `Objective`, `Tier`, `ProjectStage`, etc.

Let's try to confirm a minimal set of essential fields at this point.

So, for example - it would be great if you could confirm like so (don't worry about Django internals like `id` and `slug`, etc), putting the class of the field in brackets if necessary:

```
Project:
- name
- tier (Tier)
- project_type (ProjectType)
```
etc.

If a dependent class isn't already in [models.py](https://github.com/yulqen/dbasik/blob/master/dbasik/register/models.py), please define that in the same way.

I'd like to get all this `Register` nailed down as much as possible before moving on to `Return` business.

Thanks!

**Comment by banillie** [comment]
@yulqen i think we could keep this as basic as possible to start with. Let fields see: 
- Name
- Abbreviation 
- Tier (drop down options) 
- Stage (drop down options) 
- Group (drop down options) 
- Type (drop down options) 

And that's about it. These are the most common forms of meta data to group / slice and dice projects with or provide basic context. I can't think of anything else at the moment which analysis_engine uses.

**Comment by yulqen** [comment]
Ok - sounds good. Will start there. Thanks for looking.

On 18-06-2022 11:55 , Will Grant wrote:
***@***.*** i think we could keep this as basic as possible to start with. Let fields see:
>- Name
>- Abbreviation
>- Tier (drop down options)
>- Stage (drop down options)
>- Group (drop down options)
>- Type (drop down options)
>
>And that's about it. These are the most common forms of meta data to group / slice and dice projects with or provide basic context. I can't think of anything else at the moment which analysis_engine uses.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/yulqen/dbasik/issues/11#issuecomment-1159537347
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Best regards,
Matthew
