### ISSUE TITLE
api client error

### ISSUE THREAD

**Issue by banillie** [yulqen/dbasik#18]
I'm still get the error 

```
response -> 989 -> datamapline -> datamap -> tier
  none is not an allowed value (type=type_error.none.not_allowed)
```

when running `scripts/api_client.py` for some reason. My dev branch is merged with your latest dev branch. 

It might be that I'm giving the wrong financial quarter ID. Is the the ID the same as the pk?

**Comment by yulqen** [comment]
I certainly got this one!

It might still be expecting a Datamap to have a Tier, which I think you removed in your recent commit. Make sure you're using a Datamap that has been added since that change.

**Comment by banillie** [comment]
Yeap that was it. I put a Tier value in via the admin site and it worked! Cheers.You good for some more coding tomorrow?

**Comment by yulqen** [comment]
Yep, dude. Tomorrow is good.
M

On 17-11-2022 03:21 , Will Grant wrote:
>Yeap that was it. I put a Tier value in via the admin site and it worked! Cheers.You good for some more coding tomorrow?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/yulqen/dbasik/issues/18#issuecomment-1318487197
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Matthew
