### ISSUE TITLE
Implement setting data types on datamap

### ISSUE THREAD

**Issue by yulqen** [yulqen/dbasik#3]
The facility is present in the datamap schema but this is not yet implemented. It could be used to deal with a range of possible exceptions (i.e. #2), and allow for sensible warning and error messages to be flagged to the user.

**Comment by hammerheadlemon** [comment]
Working on this in [issue3_datamaps_datamatypes](https://github.com/hammerheadlemon/dbasik/tree/issue3_datamaps_datatypes) branch.

**Comment by hammerheadlemon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stuff](https://trello.com/c/PzKwKbxP/238-stuff)

**Comment by hammerheadlemon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Type checking via the Datamap](https://trello.com/c/AlGg1Dae/9-type-checking-via-the-datamap)
