### ISSUE TITLE
Dependencies - security vulnerabilities in celery and Django

### ISSUE THREAD

**Issue by yulqen** [yulqen/dbasik#5]
@banillie - fixed version issues with Django and Celery.

To update your fork, make sure you have my repo set as a remote (we'll call it "upstream") with `git remote add upstream https://github.com/yulqen/dbasik.git`. Check with `git remote -v` (you should have your fork as `origin` and mine as `upstream`.  Then you want to do a `git fetch upstream` to pull down my repo - which includes the change I made today. Then, to merge it into your fork's master - make sure you're on master (`git checkout master`) then merge with `git merge upstream/main`. If you have manually changed the `requirements.txt` file you will get a merge conflict, so probably easiest to revert this change to that file before you merge from the upstream branch.

**Comment by banillie** [comment]
@yulqen thanks. Will do this tomorrow. Cheers.

**Comment by banillie** [comment]
@yulqen done. All good. If I was to now do a `push upstream` command, will this create a pull request in your repo?

**Comment by yulqen** [comment]
You can't push to `upstream` because that is my repo and you don't have permissions to do that by default. To create a pull request, what you do is make any changes and push those commits up to **your** fork on Github, i.e. `origin`. Just a normal push as you would do anyway. From there, you can go into your fork on Github and create a pull request via the web site (it will probably ask you automatically if you want to do this - if not, go to the commit in question and you can create it from there). It's usually best to create a new branch on your form to do this but you don't have to - you could just do it on your `master`.  I will get a notification at my end saying you've made a pull request, then I can pull down your changes, test them etc and then merge into `master` if I'm happy, or whatever.

Once I've merged the changes and progressed my version, you can do a `git fetch upstream/master` again at any time and merge back into your `master` to keep up to date.

**Comment by banillie** [comment]
Trying to workout how dbasik is configured and get it running on my local machine. It's a good challenge! You seem to be using a package called celery to manage the config. Will learning/understanding more about celery help me?

**Comment by yulqen** [comment]
@banillie - Celery is an asynchronous framework for python. So that we can import and process batches of spreadsheets instead of doing one at a time.

https://docs.celeryproject.org/en/stable/getting-started/introduction.html
