### ISSUE TITLE
Creating sensible fixtures from which to spin up a test application

### ISSUE THREAD

**Issue by yulqen** [yulqen/dbasik#7]
@banillie  - not sure if you're subscribed to the project here so flagging in case you're not. Feel free to add thoughts.

When spinning up the application for testing - if we've previously destroyed the data containers, which is often, it is tedious to have to input new project, project stages, tiers, etc. We have the management command for creating financial quarters, but the question is - can we do something similar to enable us to spin up test project data?

Here are some options:

1. To create a `Project`, you also need a `Project Stage`, `Project Type` and a `Tier`.
2. To create a `Datamap`, you need a `Tier` and lots of data from a CSV file. The best way to handle this for fixtures is the same as in the application - uploading a `datamap.csv` file via the UI, I don't propose changing that.
3. Financial quarters is done.

I don't propose allowing the user of the management command to pass in parameters - it is too complex. For example, asking the user to provide a list of project names for the command would be tedious and unnecessary. This is for testing purposes only at this point - we could adapt it later for in-production use if it gets to a useful state, to allow us to create database entities from the command line, but I don't think its necessary at this point.

There is currently a requirement that the `Project` name should match the file name of a populated template you want to upload, so for testing/fixtures purposes, this needs to be factored in. It would make sense create 10 or so `Project` items - for security's sake, and because their names are going into the source code, they should all be fictional projects, which means we'd need a matching set of populated template files to test with which have matching fictional names.

Also, @banillie you mentioned in an email a few days ago a suggestion surrounding getting the project name from somewhere else. Would you be able to elaborate on that in this issue?

**Comment by banillie** [comment]
Yes totally agree with all of that and was exactly what I had in mind re my suggestion that we have a way of setting up projects each time, so doesn't need to be done manually. Cheers.

**Comment by banillie** [comment]
I should be getting notifications for this project. Maybe try responding without @ me.

**Comment by banillie** [comment]
Other things I thought we might cover tomorrow include:
- the `raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the envronment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.` which I think you're getting also?
- getting the debug set-up in pycharm 

Just ideas. Also happy if you've got other things in mind.

**Comment by yulqen** [comment]
I'm not aware of this first error. How are your opening the Python console? Do you mean the console Django gives you (`python manage.py shell`)? Either way, you need to invoke the container properly - so something like `docker-compose run --rm app sh -c "python manage.py shell"` would be required or if the `dbasik_app_1` container is already running, `docker-compose exec app sh -c "python manage.py shell"` (I think). Happy to discuss tomorrow.

**Comment by banillie** [comment]
Yes I think it's something to do with how the pycharm python console is configured. `python manage.py shell` works fine. I've had a play around with the configuration, but all pretty alien to me.

**Comment by banillie** [comment]
Still ok for some coding at 3.30 @yulqen ?

**Comment by yulqen** [comment]
Yup!
